django_extended_accounts/urls.py
from django.urls import path, include
from django.conf import settings

urlpatterns = []

## If you are using the extended_accounts app
urlpatterns += [
    path(
        "extended_accounts/",
        include("extended_accounts.urls", namespace="extended_accounts"),
    )
]
## Use this setting to correctly visualize your images in development django templates.
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extended_accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf import settings
from extended_accounts.views import (
    NewAccountView,
    AccountConfirmationView,
    DetailAccountView,
    UpdateAccountView,
    DeleteAccountView,
    RedirectAccountView,
    ListAccountView,
    DeleteProfileImageView,
)

app_name = "extended_accounts"
urlpatterns = [
    path("new_account/", NewAccountView.as_view(), name="new_account"),
    path(
        "account_confirmation/<str:username>/<token>/",
        AccountConfirmationView.as_view(),
        name="account_confirmation",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="extended_accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "detail_account/<str:username>/",
        DetailAccountView.as_view(),
        name="detail_account",
    ),
    path("list_account/", ListAccountView.as_view(), name="list_account"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("extended_accounts:redirect_account"),
            template_name="extended_accounts/password_change_form.html",
        ),
        name="password_change",
    ),
    path(
        "reset_password_request/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("extended_accounts:reset_password_request_done"),
            template_name="extended_accounts/password_reset_form.html",
            email_template_name="extended_accounts/password_reset_email.html",
            subject_template_name="extended_accounts/password_reset_subject.html",
            from_email=settings.DEFAULT_FROM_EMAIL,
        ),
        name="reset_password_request",
    ),
    path(
        "reset_password_request_done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="extended_accounts/password_reset_done.html"
        ),
        name="reset_password_request_done",
    ),
    path(
        "reset_password/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("extended_accounts:redirect_account"),
            post_reset_login=True,
            template_name="extended_accounts/password_reset_confirm.html",
        ),
        name="reset_password",
    ),
    path(
        "update_account/<str:username>",
        UpdateAccountView.as_view(),
        name="update_account",
    ),
    path(
        "delete_account/<str:username>/",
        DeleteAccountView.as_view(),
        name="delete_account",
    ),
    path(
        "delete_profile_image/<str:username>/",
        DeleteProfileImageView.as_view(),
        name="delete_profile_image",
    ),
    path("redirect_account/", RedirectAccountView.as_view(), name="redirect_account"),
]

extended_accounts/models/Profile.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from uuid import uuid4


def unique_image_name(instance, filename):
    """
    This function is used by ImageField's upload_to in order to get a unique name for an updated image, obtained via uuid4.
    WARNING: You might be tempted to use a lambda function instead of this one. That works perfectly when the application is running, but it fails when we make Django migrations. This is due to lambda functions cannot be serialized, which is a requirement for Django's migration framework. Therefore, to achieve a more consistent app, it is better to use this one.
    """
    return uuid4().hex + "." + filename.split(".")[-1]


class ProfileModel(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone_number = models.IntegerField(
        unique=True, null=True
    )  ## We have to allow null here, otherwise it'll throw an error when creating users from the CLI. Otherwise we must pass this field to the Account Model but it's not worthy of that. It's OK with theoretically allowing null but we won't allow it in forms or serializers.
    profile_image = models.ImageField(
        upload_to=unique_image_name, default=None, null=True
    )
    date_joined = models.DateTimeField(default=timezone.now)
    account = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name="profile", on_delete=models.CASCADE
    )

extended_accounts/views/AccountConfirmation.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.views.generic import View
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from extended_accounts.models import AccountModel as Account


class AccountConfirmationView(View):
    def get(self, request, **kwargs):
        ## If the account does not exist or it is already validated, we return a 404.
        ## We don't want this URL to be visited more than once per user.
        ## If everything is OK, we activate the account and redirect.
        account = get_object_or_404(Account, username=kwargs["username"])
        if account.is_active:
            raise Http404
        if default_token_generator.check_token(account, kwargs["token"]):
            account.is_active = True
            account.save()
            login(request, account)
            return HttpResponseRedirect(
                reverse_lazy("extended_accounts:redirect_account")
            )
        raise Http404

extended_accounts/views/DeleteAccount.py
from django.views.generic import DeleteView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import Http404
from extended_accounts.models import AccountModel as Account


class DeleteAccountView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Account
    template_name = "extended_accounts/delete_account.html"

    def get_success_url(self):
        return reverse_lazy("extended_accounts:login")

    def get_object(self):
        return get_object_or_404(Account, username=self.kwargs["username"])

    def test_func(self):
        account = self.get_object()
        if account != self.request.user:
            raise Http404
        return True

extended_accounts/views/DeleteProfileImage.py
from django.views.generic import View
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import Http404, HttpResponseRedirect
from extended_accounts.models import AccountModel as Account


class DeleteProfileImageView(LoginRequiredMixin, UserPassesTestMixin, View):

    def get_object(self):
        return get_object_or_404(Account, username=self.kwargs["username"])

    def post(self, *args, **kwargs):
        account = self.get_object()
        account.update(profile_image=None)
        return HttpResponseRedirect(reverse_lazy("extended_accounts:redirect_account"))

    def test_func(self):
        account = self.get_object()
        if account != self.request.user:
            raise Http404
        return True

extended_accounts/views/DetailAccount.py
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from extended_accounts.models import AccountModel as Account


class DetailAccountView(LoginRequiredMixin, DetailView):
    template_name = "extended_accounts/detail_account.html"

    def get_object(self):
        account = get_object_or_404(Account, username=self.kwargs["username"])
        return account

extended_accounts/views/ListAccount.py
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from extended_accounts.models import AccountModel as Account


class ListAccountView(LoginRequiredMixin, ListView):
    template_name = "extended_accounts/list_account.html"
    model = Account

extended_accounts/views/NewAccount.py
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.views.generic.edit import CreateView
from django.contrib.auth.tokens import default_token_generator
from django.conf import settings
from extended_accounts.helpers import NewAccountForm
from extended_accounts.models import AccountModel as Account


class NewAccountView(CreateView):
    template_name = "extended_accounts/new_account.html"
    form_class = NewAccountForm

    def get_success_url(self):
        return reverse_lazy("extended_accounts:login")

    def form_valid(self, form):
        ## Get the response of the super's form_valid
        response = super().form_valid(form)
        account = Account.objects.get(
            username=form.instance.username
        )  ## Get the account directly from the model manager. If we use form.instance directly, it doesn't have the 1to1 related Profile object because it's just a form object
        self.__send_confirmation_email(account)
        return response

    def __send_confirmation_email(self, account):
        subject = "Account Confirmation"
        message = f'Hello!\nWe have received your account creation request, follow the link {self.request.build_absolute_uri(reverse_lazy("extended_accounts:account_confirmation", kwargs = {"username": account.username, "token": default_token_generator.make_token(account)}))} to confirm your account. The link will be valid for 15 minutes, if you do not confirm the account within that time frame you will have to start the process again.'
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[account.email],
        )

extended_accounts/views/RedirectAccount.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


class RedirectAccountView(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponseRedirect(
            reverse_lazy(
                "extended_accounts:detail_account",
                kwargs={"username": request.user.username},
            )
        )

extended_accounts/views/UpdateAccount.py
from django.db.models.base import Model as Model
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from extended_accounts.models import AccountModel as Account
from extended_accounts.helpers import UpdateAccountForm


class UpdateAccountView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "extended_accounts/update_account.html"
    model = Account
    form_class = UpdateAccountForm

    def get_success_url(self):
        return reverse_lazy("extended_accounts:redirect_account")

    def get_object(self):
        return get_object_or_404(Account, username=self.kwargs["username"])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        instance = kwargs["instance"]
        kwargs["initial"] = {
            "first_name": instance.profile.first_name,
            "last_name": instance.profile.last_name,
            "phone_number": instance.profile.phone_number,
            "profile_image": instance.profile.profile_image,
        }
        return kwargs

    def test_func(self):
        user = self.get_object()
        if user != self.request.user:
            raise Http404
        return True

extended_accounts/templates/extended_accounts/delete_account.html
{% extends 'base.html' %}

{% block title %}
    Delete account
{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <button>Delete account</button>
    </form>
{% endblock content %}

extended_accounts/templates/extended_accounts/detail_account.html
{% extends 'base.html' %}

{% block title %}
Account
{% endblock %}

{% block content %}
    <ul>
        <li><p>Username: {{ object.username }}</p></li>
        <li><p>First_name: {{ object.profile.first_name }}</p></li>
        <li><p>Last_name: {{ object.profile.last_name }}</p></li>
        <li><p>E-mail: {{ object.email }}</p></li>
        <li><p>Phone_number: {{ object.profile.phone_number }}</p></li>
    </ul>
    {% if object.profile.profile_image %}
        <picture>
            <source srcset="{{ object.profile.profile_image.url }}.webp" type="image/webp">
            <img src="{{ object.profile.profile_image.url }}.png" alt="image" loading="lazy">
        </picture>
    {% endif %}
    
{% endblock %}

extended_accounts/templates/extended_accounts/list_account.html
{% extends 'base.html' %}

{% block title %}
Account
{% endblock %}

{% block content %}
    <ul>
        {% for account in object_list %}
            <li><a href="{% url 'extended_accounts:detail_account' username=account.username %}">{{ account.username }}</a></li>
        {% endfor %}
    </ul>

    
{% endblock %}

extended_accounts/templates/extended_accounts/login.html
{% extends 'base.html' %}

{% block title %}
Inicio de sesión
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Login</button>
    </form>
    <a href="{% url 'extended_accounts:new_account' %}">Not registered yet? Create an account</a>
    <a href="{% url 'extended_accounts:reset_password_request' %}">Did you forget your password?</a>
{% endblock %}

extended_accounts/templates/extended_accounts/new_account.html
{% extends 'base.html' %}

{% block title %}
    New account
{% endblock title %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create your account</button>
    </form>
{% endblock content %}

extended_accounts/templates/extended_accounts/password_change_form.html
{% extends 'base.html' %}

{% block title %}
    Change your password
{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Change password</button>
    </form>
{% endblock content %}

extended_accounts/templates/extended_accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    Reset password
{% endblock title %}

{% block content %}
    {% if validlink %}
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Reset password</button>
        </form>
    {% else %}
        <h1>This link is not longer valid. Please, request a new one if you need to reset your password</h1>
    {% endif %}

{% endblock content %}

extended_accounts/templates/extended_accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    Password reset request succeeded
{% endblock title %}

{% block content %}
    <h1>Thanks! We have sent instructions to your e-mail to reset your password</h1>
{% endblock content %}

extended_accounts/templates/extended_accounts/password_reset_email.html
New password requested for {{ user }}. :
{{ protocol}}://{{ domain }}{% url 'extended_accounts:reset_password' uidb64=uid token=token %}

extended_accounts/templates/extended_accounts/password_reset_form.html
{% extends 'base.html' %}

{% block title %}
    Reset Password Request
{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Request new password</button>
    </form>
{% endblock content %}

extended_accounts/templates/extended_accounts/password_reset_subject.html
Password reset requested

extended_accounts/templates/extended_accounts/update_account.html
{% extends 'base.html' %}

{% block title %}
    Update account
{% endblock title %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Update your account</button>
    </form>
{% endblock content %}